# .streamlit/config.toml

[theme]
primaryColor = "#FFCB05"  # Electric yellow
backgroundColor = "#3B4CCA"  # Blue
secondaryBackgroundColor = "#FFDE00"  # Lighter Yellow
textColor = "#5390D9"  # Lighter blue for readability
font = "sans serif"
